[package]
name = "ethereum_rust-l2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12.7", features = ["json"] }
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
ethereum-types.workspace = true
ethereum_rust-core.workspace = true
ethereum_rust-rlp.workspace = true
ethereum_rust-rpc.workspace = true
ethereum_rust-blockchain.workspace = true
ethereum_rust-storage.workspace = true
hex.workspace = true
bytes.workspace = true
jsonwebtoken.workspace = true
sp1-sdk = "2.0.0"
libsecp256k1 = "0.7.1"
keccak-hash = "0.10.0"
envy = "0.4.2"

[lib]
path = "./l2.rs"
