[workspace]
members = ["bench/revm_comparison"]

[package]
name = "ethereum_rust-levm_mlir"
edition = "2021"

[dependencies]
llvm-sys = "181.0.0"
melior = { version = "0.18.4", features = ["ods-dialects"] }
mlir-sys = "0.2.2"
num-bigint = "0.4.5"
sha3 = "0.10.8"
thiserror = "1.0.57"
ethereum-types = "0.14.1"
bytes = { version = "1.6.0", features = ["serde"] }
bitflags = "2.5.0"
secp256k1 = { version = "0.29.0", features = ["recovery"] }
sha2 = "0.10.8"
ripemd = "0.1.3"
lambdaworks-math = "0.10.0"

[dev-dependencies]
hex-literal = "0.4.1"
rstest = "0.21.0"
serde = { version = "1.0.203", features = ["derive", "rc"] }
serde_json = { version = "1.0.117" }
walkdir = "2.5.0"
datatest-stable = "0.2.9"
hex = "0.4.3"

[build-dependencies]
cc = "1.0.83"

[[test]]
name = "time_consuming"
path = "tests/time_consuming_test.rs"
harness = false

[[test]]
name = "normal"
path = "tests/ef_tests.rs"
harness = false

[[test]]
name = "blake2B"
path = "tests/blake2B_test.rs"
harness = false
