[package]
name = "revm_comparison"
version = "0.1.0"
edition = "2021"

[lib]
name = "revm_comparison"
path = "src/lib.rs"

[dependencies]
ethereum_rust-levm_mlir = { path = "../../" }
hex = "0.4.3"
revm = "9.0.0"

[[bin]]
name="levm_mlir_factorial"
path="src/levm_mlir_factorial.rs"

[[bin]]
name="revm_factorial"
path="src/revm_factorial.rs"

[[bin]]
name="levm_mlir_fibonacci"
path="src/levm_mlir_fibonacci.rs"

[[bin]]
name="revm_fibonacci"
path="src/revm_fibonacci.rs"
