name: Ethereum Foundation Tests

on:
  merge_group:
  push:
    paths:
      - 'crates/vm/levm/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'crates/vm/levm/**'
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.79.0

jobs:
    ethereum-tests:
        name: Ethereum Tests (Ubuntu)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
              with:
                toolchain: ${{ env.RUST_VERSION }}
                components: clippy

            - name: Set up cargo cache
              uses: Swatinem/rust-cache@v2

            - name: Install Link deps
              run: sudo apt-get install libc-dev build-essential

            - name: Install testing tools
              uses: taiki-e/install-action@v2
              with:
                tool: cargo-nextest

            - name: Download test vectors
              run: | 
                cd crates/vm/levm
                make ethtests

            - name: Run Ethereum Foundation tests
              run: | 
                cd crates/vm/levm
                make test-eth
